services:
    louvre_booking.calculate_price:
        class: Louvre\BookingBundle\Services\CalculatePrice
    louvre_booking.booking_number:
        class: Louvre\BookingBundle\Services\BookingNumber
    louvre_booking.stripe:
        class: Louvre\BookingBundle\Services\Stripe
#        arguments: ["@service_id", "plain_value", "%parameter%"]
