<?php

namespace Louvre\BookingBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
	public function totalPrice()
	{
		$qb = $this->createQueryBuilder('b')
			->innerjoin('b.buyer', 'book')
			->addselect('book')
			->select('sum(b.price)')
			->where('b.buyer = book.id')
		;

		return $qb->getQuery()->getSingleScalarResult();
	}
}
