<?php

namespace Louvre\BookingBundle\Repository;

/**
 * BuyerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyerRepository extends \Doctrine\ORM\EntityRepository
{
	public function totalBooking()
	{
		$qb = $this->createQueryBuilder('b')
			->select('b.date')
			->groupBy('b.date')
			->having('sum(b.quantity) >= 1000')
		;

		return $qb->getQuery()->getArrayResult();
	}
}
